"""Create initial tables

Revision ID: 84f99e3be8a6
Revises: f5e34b085318
Create Date: 2025-11-14 01:08:19.544274

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '84f99e3be8a6'
down_revision: Union[str, None] = 'f5e34b085318'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('countries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.Enum('US', 'BR', 'MX', 'ID', 'PH', 'VN', 'PK', 'BD', 'EG', 'NG', 'TH', 'JP', 'UK', 'DE', 'FR', name='countrycode'), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('users_in_millions', sa.Float(), nullable=False),
    sa.Column('growth_rate', sa.Float(), nullable=False),
    sa.Column('timezone', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_country_active', 'countries', ['is_active'], unique=False)
    op.create_index('idx_country_code', 'countries', ['code'], unique=False)
    op.create_index(op.f('ix_countries_code'), 'countries', ['code'], unique=True)
    op.create_index(op.f('ix_countries_is_active'), 'countries', ['is_active'], unique=False)
    op.create_table('creators',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tiktok_creator_id', sa.String(length=100), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=True),
    sa.Column('profile_url', sa.String(length=500), nullable=True),
    sa.Column('profile_image', sa.String(length=500), nullable=True),
    sa.Column('followers', sa.BigInteger(), nullable=False),
    sa.Column('follower_growth', sa.Float(), nullable=False),
    sa.Column('videos_count', sa.Integer(), nullable=False),
    sa.Column('likes_count', sa.BigInteger(), nullable=False),
    sa.Column('average_engagement', sa.Float(), nullable=False),
    sa.Column('country_id', sa.Integer(), nullable=False),
    sa.Column('is_trending', sa.Boolean(), nullable=False),
    sa.Column('trending_rank', sa.Integer(), nullable=True),
    sa.Column('first_seen', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('last_seen', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['country_id'], ['countries.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tiktok_creator_id')
    )
    op.create_index('idx_creator_country_trending', 'creators', ['country_id', 'is_trending'], unique=False)
    op.create_index('idx_creator_tiktok_id', 'creators', ['tiktok_creator_id'], unique=False)
    op.create_index(op.f('ix_creators_followers'), 'creators', ['followers'], unique=False)
    op.create_index(op.f('ix_creators_last_seen'), 'creators', ['last_seen'], unique=False)
    op.create_table('hashtags',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('country_id', sa.Integer(), nullable=False),
    sa.Column('niche', sa.Enum('BOOKTOK', 'HEALTHTOK', 'DIYTOK', 'GAMINGTOK', 'FINANCETOK', 'MUSICTOK', 'COMEDYTOK', 'ACTIVISMTOK', 'FOODTOK', 'BEAUTYTOK', 'FASHIONTOK', 'DANCETOK', 'COMMERCETOK', 'EDUCATIONTOK', 'LIFESTYLETOK', 'TRAVELLTOK', 'ENTERTAINMENTTOK', 'ARTTOK', 'ENTREPRENEURTOK', name='nichetype'), nullable=False),
    sa.Column('posts_count', sa.Integer(), nullable=False),
    sa.Column('views_count', sa.BigInteger(), nullable=False),
    sa.Column('engagement_rate', sa.Float(), nullable=False),
    sa.Column('growth_rate', sa.Float(), nullable=False),
    sa.Column('viral_score', sa.Integer(), nullable=False),
    sa.Column('trend_direction', sa.Enum('UP', 'DOWN', 'STABLE', name='trenddirection'), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('previous_rank', sa.Integer(), nullable=True),
    sa.Column('data_source', sa.Enum('OFFICIAL_API', 'CREATIVE_CENTER', 'PLAYWRIGHT_SCRAPER', name='datasourcetype'), nullable=False),
    sa.Column('first_seen', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('last_seen', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['country_id'], ['countries.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_hashtag_country_niche', 'hashtags', ['country_id', 'niche'], unique=False)
    op.create_index('idx_hashtag_name_country', 'hashtags', ['name', 'country_id'], unique=True)
    op.create_index('idx_hashtag_rank_country', 'hashtags', ['rank', 'country_id'], unique=False)
    op.create_index(op.f('ix_hashtags_growth_rate'), 'hashtags', ['growth_rate'], unique=False)
    op.create_index(op.f('ix_hashtags_last_seen'), 'hashtags', ['last_seen'], unique=False)
    op.create_table('sounds',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tiktok_sound_id', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('artist', sa.String(length=200), nullable=True),
    sa.Column('usage_count', sa.Integer(), nullable=False),
    sa.Column('growth_rate', sa.Float(), nullable=False),
    sa.Column('viral_score', sa.Float(), nullable=False),
    sa.Column('country_id', sa.Integer(), nullable=False),
    sa.Column('niche', sa.Enum('BOOKTOK', 'HEALTHTOK', 'DIYTOK', 'GAMINGTOK', 'FINANCETOK', 'MUSICTOK', 'COMEDYTOK', 'ACTIVISMTOK', 'FOODTOK', 'BEAUTYTOK', 'FASHIONTOK', 'DANCETOK', 'COMMERCETOK', 'EDUCATIONTOK', 'LIFESTYLETOK', 'TRAVELLTOK', 'ENTERTAINMENTTOK', 'ARTTOK', 'ENTREPRENEURTOK', name='nichetype'), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('trend_direction', sa.Enum('UP', 'DOWN', 'STABLE', name='trenddirection'), nullable=False),
    sa.Column('first_seen', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('last_seen', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['country_id'], ['countries.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tiktok_sound_id')
    )
    op.create_index('idx_sound_country_rank', 'sounds', ['country_id', 'rank'], unique=False)
    op.create_index('idx_sound_growth_rate', 'sounds', ['growth_rate'], unique=False)
    op.create_index('idx_sound_tiktok_country', 'sounds', ['tiktok_sound_id', 'country_id'], unique=True)
    op.create_index(op.f('ix_sounds_last_seen'), 'sounds', ['last_seen'], unique=False)
    op.create_table('trends',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('country_id', sa.Integer(), nullable=False),
    sa.Column('niche', sa.Enum('BOOKTOK', 'HEALTHTOK', 'DIYTOK', 'GAMINGTOK', 'FINANCETOK', 'MUSICTOK', 'COMEDYTOK', 'ACTIVISMTOK', 'FOODTOK', 'BEAUTYTOK', 'FASHIONTOK', 'DANCETOK', 'COMMERCETOK', 'EDUCATIONTOK', 'LIFESTYLETOK', 'TRAVELLTOK', 'ENTERTAINMENTTOK', 'ARTTOK', 'ENTREPRENEURTOK', name='nichetype'), nullable=False),
    sa.Column('viral_score', sa.Float(), nullable=False),
    sa.Column('momentum', sa.Float(), nullable=False),
    sa.Column('sentiment', sa.Enum('POSITIVE', 'NEGATIVE', 'NEUTRAL', name='sentimenttype'), nullable=False),
    sa.Column('start_date', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('peak_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['country_id'], ['countries.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_trend_country_active', 'trends', ['country_id', 'is_active'], unique=False)
    op.create_index('idx_trend_viral_score', 'trends', ['viral_score'], unique=False)
    op.create_index(op.f('ix_trends_start_date'), 'trends', ['start_date'], unique=False)
    op.create_index(op.f('ix_trends_viral_score'), 'trends', ['viral_score'], unique=False)
    op.create_table('trend_creators',
    sa.Column('trend_id', sa.Integer(), nullable=False),
    sa.Column('creator_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['creator_id'], ['creators.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['trend_id'], ['trends.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('trend_id', 'creator_id')
    )
    op.create_table('trend_hashtags',
    sa.Column('trend_id', sa.Integer(), nullable=False),
    sa.Column('hashtag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['hashtag_id'], ['hashtags.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['trend_id'], ['trends.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('trend_id', 'hashtag_id')
    )
    op.create_table('trend_sounds',
    sa.Column('trend_id', sa.Integer(), nullable=False),
    sa.Column('sound_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['sound_id'], ['sounds.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['trend_id'], ['trends.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('trend_id', 'sound_id')
    )
    op.create_table('videos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tiktok_video_id', sa.String(length=100), nullable=False),
    sa.Column('creator_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('description', sa.String(length=2000), nullable=True),
    sa.Column('views', sa.BigInteger(), nullable=False),
    sa.Column('likes', sa.BigInteger(), nullable=False),
    sa.Column('comments', sa.BigInteger(), nullable=False),
    sa.Column('shares', sa.BigInteger(), nullable=False),
    sa.Column('bookmarks', sa.BigInteger(), nullable=False),
    sa.Column('engagement_rate', sa.Float(), nullable=False),
    sa.Column('viral_score', sa.Float(), nullable=False),
    sa.Column('country_id', sa.Integer(), nullable=False),
    sa.Column('music_id', sa.String(length=100), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('tiktok_created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['country_id'], ['countries.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['creator_id'], ['creators.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tiktok_video_id')
    )
    op.create_index('idx_video_country', 'videos', ['country_id'], unique=False)
    op.create_index('idx_video_creator', 'videos', ['creator_id'], unique=False)
    op.create_index('idx_video_tiktok_id', 'videos', ['tiktok_video_id'], unique=False)
    op.create_index(op.f('ix_videos_creator_id'), 'videos', ['creator_id'], unique=False)
    op.create_index(op.f('ix_videos_tiktok_created_at'), 'videos', ['tiktok_created_at'], unique=False)
    op.create_index(op.f('ix_videos_viral_score'), 'videos', ['viral_score'], unique=False)
    op.create_table('sound_videos',
    sa.Column('sound_id', sa.Integer(), nullable=False),
    sa.Column('video_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['sound_id'], ['sounds.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('sound_id', 'video_id')
    )
    op.create_table('video_hashtags',
    sa.Column('video_id', sa.Integer(), nullable=False),
    sa.Column('hashtag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['hashtag_id'], ['hashtags.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('video_id', 'hashtag_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('video_hashtags')
    op.drop_table('sound_videos')
    op.drop_index(op.f('ix_videos_viral_score'), table_name='videos')
    op.drop_index(op.f('ix_videos_tiktok_created_at'), table_name='videos')
    op.drop_index(op.f('ix_videos_creator_id'), table_name='videos')
    op.drop_index('idx_video_tiktok_id', table_name='videos')
    op.drop_index('idx_video_creator', table_name='videos')
    op.drop_index('idx_video_country', table_name='videos')
    op.drop_table('videos')
    op.drop_table('trend_sounds')
    op.drop_table('trend_hashtags')
    op.drop_table('trend_creators')
    op.drop_index(op.f('ix_trends_viral_score'), table_name='trends')
    op.drop_index(op.f('ix_trends_start_date'), table_name='trends')
    op.drop_index('idx_trend_viral_score', table_name='trends')
    op.drop_index('idx_trend_country_active', table_name='trends')
    op.drop_table('trends')
    op.drop_index(op.f('ix_sounds_last_seen'), table_name='sounds')
    op.drop_index('idx_sound_tiktok_country', table_name='sounds')
    op.drop_index('idx_sound_growth_rate', table_name='sounds')
    op.drop_index('idx_sound_country_rank', table_name='sounds')
    op.drop_table('sounds')
    op.drop_index(op.f('ix_hashtags_last_seen'), table_name='hashtags')
    op.drop_index(op.f('ix_hashtags_growth_rate'), table_name='hashtags')
    op.drop_index('idx_hashtag_rank_country', table_name='hashtags')
    op.drop_index('idx_hashtag_name_country', table_name='hashtags')
    op.drop_index('idx_hashtag_country_niche', table_name='hashtags')
    op.drop_table('hashtags')
    op.drop_index(op.f('ix_creators_last_seen'), table_name='creators')
    op.drop_index(op.f('ix_creators_followers'), table_name='creators')
    op.drop_index('idx_creator_tiktok_id', table_name='creators')
    op.drop_index('idx_creator_country_trending', table_name='creators')
    op.drop_table('creators')
    op.drop_index(op.f('ix_countries_is_active'), table_name='countries')
    op.drop_index(op.f('ix_countries_code'), table_name='countries')
    op.drop_index('idx_country_code', table_name='countries')
    op.drop_index('idx_country_active', table_name='countries')
    op.drop_table('countries')
    # ### end Alembic commands ###
